// <auto-generated />
using System;
using COOPED.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COOPED.Infrastructure.Migrations
{
    [DbContext(typeof(CoopedDbContext))]
    [Migration("20260709165322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("COOPED.Domain.Entities.Administrateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Administrateurs");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCarnet")
                        .HasColumnType("date");

                    b.Property<string>("NomCli")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomPersonneAPrevenir")
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomCli")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Profession")
                        .HasColumnType("longtext");

                    b.Property<int>("PromoteurId")
                        .HasColumnType("int");

                    b.Property<string>("Quartier")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexe")
                        .HasColumnType("longtext");

                    b.Property<string>("TelPersonneAPrevenir")
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PromoteurId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Penalite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PretId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PretId");

                    b.ToTable("Penalites");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Promoteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Promoteurs");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Tontine", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numero"));

                    b.Property<int?>("AchatId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<decimal>("Mise")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NbreMise")
                        .HasColumnType("int");

                    b.Property<int?>("PretId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("ClientId");

                    b.ToTable("Tontines");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TypeTransaction")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Transaction");

                    b.HasDiscriminator<string>("TypeTransaction").HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Achat", b =>
                {
                    b.HasBaseType("COOPED.Domain.Entities.Transaction");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TontineId")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasIndex("TontineId")
                        .IsUnique();

                    b.ToTable("Transaction", t =>
                        {
                            t.Property("TontineId")
                                .HasColumnName("Achat_TontineId");
                        });

                    b.HasDiscriminator().HasValue("Achat");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Cotisation", b =>
                {
                    b.HasBaseType("COOPED.Domain.Entities.Transaction");

                    b.Property<int>("NbreMise")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TontineId")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasIndex("TontineId");

                    b.ToTable("Transaction", t =>
                        {
                            t.Property("TontineId")
                                .HasColumnName("Cotisation_TontineId");
                        });

                    b.HasDiscriminator().HasValue("Cotisation");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Frais", b =>
                {
                    b.HasBaseType("COOPED.Domain.Entities.Transaction");

                    b.Property<int?>("PretId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("ClientId");

                    b.HasIndex("PretId");

                    b.ToTable("Transaction", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Frais_Type");
                        });

                    b.HasDiscriminator().HasValue("Frais");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Pret", b =>
                {
                    b.HasBaseType("COOPED.Domain.Entities.Transaction");

                    b.Property<DateOnly>("DateEcheance")
                        .HasColumnType("date");

                    b.Property<int>("DureeRemboursement")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int?>("TontineId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasIndex("ClientId");

                    b.HasIndex("TontineId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Pret");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Retrait", b =>
                {
                    b.HasBaseType("COOPED.Domain.Entities.Transaction");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Motif")
                        .HasColumnType("longtext");

                    b.HasIndex("ClientId");

                    b.HasDiscriminator().HasValue("Retrait");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Client", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Promoteur", "Promoteur")
                        .WithMany("Clients")
                        .HasForeignKey("PromoteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promoteur");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Penalite", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Pret", "Pret")
                        .WithMany("Penalites")
                        .HasForeignKey("PretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pret");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Tontine", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany("Tontines")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Achat", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany("Achats")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPED.Domain.Entities.Tontine", "Tontine")
                        .WithOne("Achat")
                        .HasForeignKey("COOPED.Domain.Entities.Achat", "TontineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Cotisation", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPED.Domain.Entities.Tontine", "Tontine")
                        .WithMany("Cotisations")
                        .HasForeignKey("TontineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Frais", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany("FraisList")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPED.Domain.Entities.Pret", "Pret")
                        .WithMany()
                        .HasForeignKey("PretId");

                    b.Navigation("Client");

                    b.Navigation("Pret");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Pret", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany("Prets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COOPED.Domain.Entities.Tontine", "Tontine")
                        .WithOne("Pret")
                        .HasForeignKey("COOPED.Domain.Entities.Pret", "TontineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Tontine");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Retrait", b =>
                {
                    b.HasOne("COOPED.Domain.Entities.Client", "Client")
                        .WithMany("Retraits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Client", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("FraisList");

                    b.Navigation("Prets");

                    b.Navigation("Retraits");

                    b.Navigation("Tontines");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Promoteur", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Tontine", b =>
                {
                    b.Navigation("Achat");

                    b.Navigation("Cotisations");

                    b.Navigation("Pret");
                });

            modelBuilder.Entity("COOPED.Domain.Entities.Pret", b =>
                {
                    b.Navigation("Penalites");
                });
#pragma warning restore 612, 618
        }
    }
}
